// <auto-generated />
namespace POC_Sistema_Ventas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CategoriaYProducto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CategoriaYProducto));
        
        string IMigrationMetadata.Id
        {
            get { return "202105011804119_CategoriaYProducto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
